version: '3'
services:
  nginx:
    image: palish12ish34/nginx
    stdin_open: true
    tty: true
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8090:8090
    depends_on:
      - frontend
  backend:
    build: ./meterm-backend
    ports:
      - 4008:4008
    links:
      - db
  frontend:
    build: ./cy-appp
    ports:
      - 3000:3000
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - electricity:/data/db
volumes:
  electricity: