version: '3'
services:
  nginx:
    image: palish12ish34/nginx
    stdin_open: true
    tty: true
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
  backend:
    build: ./meterm-backend
    ports:
      - 4008:4008
  frontend:
    build: ./cy-appp
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb+srv://pauline:p12ish34@cluster0.anzcs.mongodb.net/electricity
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - electricity:/data/db
volumes:
  electricity: