version: '3.3'
services:
  backend:
    build:
      context: backend/meterm-backend
      dockerfile: Dockerfile
    ports:
        - '4008:4008'
    
  frontend:
    build:
      context: frontend/cy-appp
      dockerfile: Dockerfile
    ports:
        - '3000:3000'
    
  db:
    build:
     context: mongodb
     dockerfile: Dockerfile
   
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
volumes:
    db: