version: '3.3'
services:
  backend:
    build:
      context: backend/meterm-backend
      dockerfile: Dockerfile
    ports:
        - '4008:4008'
    links:
      - mongo 
  frontend:
    build:
      context: frontend/electricity-front
      dockerfile: Dockerfile
    ports:
        - '3000:3000'
    links : 
     - backend
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
volumes:
    db: